apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courseapi
  template:
    metadata:
      labels:
        app: courseapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: courseapi
          image: tfacr0719.azurecr.io/courseapi:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: courseapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: courseapi
