apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapi
  template:
    metadata:
      labels:
        app: tasksapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: tasksapi
          image: razniceguy/taskapi:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tasksapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: tasksapi
